services:
  db:
    image: postgres:12
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  app:
    build: .
    container_name: laravel
    restart: always
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes: 
      - ./src:/var/www/laravel
    ports:
      - 8000:8000
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - 15672:15672


volumes: 
  postgres-data: